const data = {
    produtos:[
        {
            _id: '1',
            name: 'Betoneira 400L BM-400',
            categoria: 'Betoneira',
            imagem: '/images/p1.jpg',
            price: 3999.50,
            marca: 'HORBACH',
            rating: 4.5,
            numReviews: 10,
            description: 'Produto de alta qualidade',
        },
        {
            _id: '2',
            name: 'Capa para Respirar na Água',
            categoria: 'Produtos Mágicos',
            imagem: '/images/p2.jpg',
            price:  256,
            marca: 'HogwartsLTDA',
            rating: 4.0,
            numReviews: 14,
            description: 'Item maravilhoso, incomum!',
        },
        {
            _id: '3',
            name: 'Caneta Seringa',
            categoria: 'Canetas',
            imagem: '/images/p3.png',
            price: 15,
            marca: 'BIC',
            rating: 2,
            numReviews: 17,
            description: 'Caneta sem tinta',
        },
        {
            _id: '4',
            name: 'Harpas douradas',
            categoria: 'Instrumentos Musicais',
            imagem: '/images/p4.jpg',
            price: 220000,
            marca: 'Harpicas',
            rating: 5,
            numReviews: 14,
            description: 'Magnífica Harpa!',
        },
        {
            _id: '5',
            name: 'Chapéu de disfarce',
            categoria: 'Chapéus',
            imagem: '/images/p5.png',
            price: 123.40,
            marca: 'Raio Laser',
            rating: 3,
            numReviews: 10,
            description: 'Item maravilhoso, incomum! (requer sintonização)',
        },
        {
            _id: '6',
            name: 'Caneta BRADOCK',
            categoria: 'Canetas',
            imagem: '/images/p6.jpg',
            price: 12,
            marca: 'Montegrappa',
            rating: 4.5,
            numReviews: 15,
            description: 'Aquela caneta que muda uma vida!',
        },
    ],
};